import type { MetadataRoute } from "next";

const BASE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://techbaria.com";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Allow search engines to crawl storefront & marketing pages
      {
        userAgent: "Googlebot",
        allow: [
          "/storefront",
          "/storefront/shop",
          "/storefront/p/",
          "/storefront/search",
          "/landing",
          "/pricing",
        ],
        disallow: [
          "/api/",
          "/pos",
          "/dashboard",
          "/admin",
          "/products",
          "/inventory",
          "/sales",
          "/purchases",
          "/customers",
          "/suppliers",
          "/accounts",
          "/expenses",
          "/reports",
          "/settings",
          "/notifications",
          "/login",
          "/register",
          "/forgot-password",
          "/reset-password",
          "/storefront/cart",
          "/storefront/checkout",
          "/storefront/account",
          "/storefront/wishlist",
          "/storefront/compare",
          "/storefront/track",
          "/storefront/order/",
        ],
      },
      {
        userAgent: "Bingbot",
        allow: [
          "/storefront",
          "/storefront/shop",
          "/storefront/p/",
          "/landing",
          "/pricing",
        ],
        disallow: [
          "/api/",
          "/pos",
          "/dashboard",
          "/login",
          "/register",
          "/storefront/cart",
          "/storefront/checkout",
          "/storefront/account",
        ],
      },
      {
        userAgent: "Twitterbot",
        allow: [
          "/storefront",
          "/storefront/p/",
        ],
        disallow: ["/api/", "/pos", "/dashboard", "/login", "/register"],
      },
      {
        userAgent: "facebookexternalhit",
        allow: [
          "/storefront",
          "/storefront/p/",
        ],
        disallow: ["/api/", "/pos", "/dashboard", "/login", "/register"],
      },
      // Default rule — block everything except public pages
      {
        userAgent: "*",
        allow: [
          "/storefront",
          "/storefront/shop",
          "/storefront/p/",
          "/landing",
          "/pricing",
        ],
        disallow: [
          "/api/",
          "/pos",
          "/dashboard",
          "/admin",
          "/products",
          "/inventory",
          "/sales",
          "/purchases",
          "/customers",
          "/suppliers",
          "/accounts",
          "/expenses",
          "/reports",
          "/settings",
          "/notifications",
          "/login",
          "/register",
          "/forgot-password",
          "/reset-password",
          "/storefront/cart",
          "/storefront/checkout",
          "/storefront/account",
          "/storefront/wishlist",
          "/storefront/compare",
          "/storefront/track",
          "/storefront/order/",
        ],
      },
    ],
    sitemap: `${BASE}/sitemap.xml`,
  };
}
